version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-fastapi
    ports:
      - "5432:5432"

  fastapi-app:
    build:
      context: .
    volumes:
      # Mount the local app directory to the /code/app directory in the container    
      - ./app:/code/app
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - MODE
      - DATABASE_URL

